FROM python:3.7

MAINTANER Your Name "nicolaj.schmit@hotmail.com"

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

COPY . /home/site/wwwroot

RUN apt-get update && \
	apt-get install gunicorn -y

WORKDIR /home/site/wwwroot
RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["gunicorn", "-b", "0.0.0.0:8000", "mealapp:app"]
